version: '3.8'

services:
  web:
    
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data